export const languagesWords = {
  en: 'English',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
  it: 'Italian',
  ja: 'Japanese',
  zh: 'Chinese',
  ar: 'Arabic',
  ru: 'Russian',
  pt: 'Portuguese',
  hi: 'Hindi',
  bn: 'Bengali',
  ko: 'Korean',
  vi: 'Vietnamese',
  tr: 'Turkish',
  fa: 'Persian',
  ur: 'Urdu',
  th: 'Thai',
  ms: 'Malay',
  id: 'Indonesian',
  nl: 'Dutch',
  sv: 'Swedish',
  no: 'Norwegian',
  da: 'Danish',
  fi: 'Finnish',
  el: 'Greek',
  he: 'Hebrew',
  hu: 'Hungarian',
  pl: 'Polish',
  ro: 'Romanian',
  cs: 'Czech',
  sk: 'Slovak',
  bg: 'Bulgarian',
  uk: 'Ukrainian',
  sr: 'Serbian',
  hr: 'Croatian',
  lt: 'Lithuanian',
  lv: 'Latvian',
  et: 'Estonian',
  sl: 'Slovenian',
  is: 'Icelandic',
  ga: 'Irish',
  mt: 'Maltese',
};

export const DISPLAY_PER_IMAGE = 10;
